#!/usr/bin/env python3
"""
run_faserps.py -- run FASERG4's `faserps` simulation with a macro built
as an in-memory Python string, piped straight to the executable's stdin.
No .mac file is ever written to disk.

Why: FASERG4/ used to carry ~17 run*.mac files (RunFASER_newgeo.mac,
runFASER_1.mac, runFASER_muon.mac, runFASER_V5.mac, ...), almost all
leftovers from earlier detector geometries -- and nothing stopped
faserps from being run with a stale one, silently simulating the wrong
detector. This script replaces all of them: the one macro that matches
the current V10 geometry lives here as build_v10_macro(), a parametrized
function, and its text is piped to `faserps -` (a new mode added to
faserps.cc that reads G4 UI commands from stdin instead of
/control/execute'ing a file). A future "run variant" is a new function
(or new keyword arguments to this one), not a new file to keep in sync
by hand.

Usage:
    python3 run_faserps.py                        # defaults matching the old runFASER_V10.mac
    python3 run_faserps.py --n-events 500 --start-event 100
    python3 run_faserps.py --input-file some_other_sample.root
    python3 run_faserps.py --print-macro           # print the macro, don't run it
    python3 run_faserps.py --vis                   # interactive G4 UI (unrelated to the macro)
    python3 run_faserps.py --build-dir PATH        # override the build/ location
"""
import argparse
import subprocess
import sys
from pathlib import Path

FASERG4_DIR = Path(__file__).resolve().parent
REPO_ROOT = FASERG4_DIR.parent
DEFAULT_BUILD_DIR = REPO_ROOT / "build"


def build_v10_macro(
    *,
    scint_size_x_cm: float = 48.0,
    scint_size_y_cm: float = 48.0,
    scint_size_z_cm: float = 20.0,
    scint_voxel_mm: float = 10.0,
    targetw_size_x_cm: float = 48.0,
    targetw_size_y_cm: float = 48.0,
    targetw_size_z_mm: float = 5.0,
    n_layers: int = 10,
    los_shift_x_cm: float = 45.0,
    los_shift_y_cm: float = 24.0,
    tilt_deg: float = -4.5,
    tracking_verbose: int = 0,
    run_verbose: int = 0,
    control_verbose: int = 0,
    n_threads: int = 1,
    input_root_file: str = "FASERMC-PO-Run10000-0_53954_3DCAL.root",
    start_event: int = 0,
    n_events: int = 100,
) -> str:
    """Builds the V10-geometry macro as a string. Defaults match the old
    runFASER_V10.mac exactly; pass keyword overrides for a variant instead
    of hand-editing a copy of a .mac file."""
    return f"""# V10 geometry, tilted -- generated by run_faserps.build_v10_macro(), not a .mac file
/FASER/scint/sizeX {scint_size_x_cm:g} cm
/FASER/scint/sizeY {scint_size_y_cm:g} cm
/FASER/scint/sizeZ {scint_size_z_cm:g} cm
/FASER/scint/voxel {scint_voxel_mm:g} mm
/FASER/targetW/sizeX {targetw_size_x_cm:g} cm
/FASER/targetW/sizeY {targetw_size_y_cm:g} cm
/FASER/targetW/sizeZ {targetw_size_z_mm:g} mm
/FASER/layers {n_layers}
/FASER/LOS/shiftX {los_shift_x_cm:g} cm
/FASER/LOS/shiftY {los_shift_y_cm:g} cm
/FASER/tiltY {tilt_deg:g} deg
#
/tracking/verbose {tracking_verbose}
/run/verbose {run_verbose}
/control/verbose {control_verbose}
/run/numberOfThreads {n_threads}
/run/initialize
/generator/rootinputfilename {input_root_file}
/generator/startevent {start_event}
/run/beamOn {n_events}
"""


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run FASERG4's faserps with the V10 macro, built as a "
                     "Python string and piped to stdin -- no .mac file involved.",
    )
    parser.add_argument("--build-dir", type=Path, default=DEFAULT_BUILD_DIR,
                         help=f"CMake build directory containing bin/faserps (default: {DEFAULT_BUILD_DIR})")
    parser.add_argument("--vis", action="store_true",
                         help="Launch faserps' interactive Geant4 UI (`faserps vis`) instead of "
                              "piping a macro. No macro is used in this mode.")
    parser.add_argument("--print-macro", action="store_true",
                         help="Print the resolved macro text and exit without running faserps.")
    parser.add_argument("--dry-run", action="store_true",
                         help="Print the command (and the macro) but don't execute it.")

    # The handful of parameters actually worth varying run-to-run; the
    # rest of build_v10_macro()'s keyword arguments cover the geometry
    # constants and are left at their V10 defaults unless you call the
    # function yourself from a custom script.
    parser.add_argument("--input-file", default="FASERMC-PO-Run10000-0_53954_3DCAL.root",
                         help="Value for /generator/rootinputfilename (relative to FASERG4/).")
    parser.add_argument("--start-event", type=int, default=0,
                         help="Value for /generator/startevent.")
    parser.add_argument("--n-events", type=int, default=100,
                         help="Value for /run/beamOn.")
    parser.add_argument("--tilt-deg", type=float, default=-4.5,
                         help="Value for /FASER/tiltY (degrees).")
    parser.add_argument("--shift-x-cm", type=float, default=45.0,
                         help="Value for /FASER/LOS/shiftX (cm).")
    parser.add_argument("--shift-y-cm", type=float, default=24.0,
                         help="Value for /FASER/LOS/shiftY (cm).")
    return parser.parse_args()


def main():
    args = parse_args()

    macro_text = build_v10_macro(
        input_root_file=args.input_file,
        start_event=args.start_event,
        n_events=args.n_events,
        tilt_deg=args.tilt_deg,
        los_shift_x_cm=args.shift_x_cm,
        los_shift_y_cm=args.shift_y_cm,
    )

    if args.print_macro:
        print(macro_text, end="")
        return 0

    binary_path = args.build_dir / "bin" / "faserps"
    if not binary_path.is_file():
        sys.exit(
            f"error: faserps binary not found: {binary_path}\n"
            f"       (build it first, e.g. `cmake --build {args.build_dir} --target faserps`)"
        )
    if not (binary_path.stat().st_mode & 0o111):
        sys.exit(f"error: {binary_path} is not executable")

    # faserps writes its TcalEvent ROOT output to a relative "output/..."
    # path (see CoreUtils/TcalEvent.cc), which ROOT's TFile will NOT
    # create for you -- if it's missing, the run fails partway through
    # with a confusing ROOT error instead of a clear one up front.
    (FASERG4_DIR / "output").mkdir(exist_ok=True)

    command = [str(binary_path), "vis" if args.vis else "-"]

    print(f"[run_faserps] working directory: {FASERG4_DIR}")
    print(f"[run_faserps] command:           {' '.join(command)}")
    if not args.vis:
        print("[run_faserps] macro (piped via stdin, not written to disk):")
        print("  " + macro_text.strip().replace("\n", "\n  "))

    if args.dry_run:
        print("[run_faserps] --dry-run: not executing.")
        return 0

    # cwd=FASERG4_DIR because the macro's /generator/rootinputfilename and
    # the output/ directory above are relative paths that only resolve
    # correctly from here (same as the GDML faserps writes out).
    if args.vis:
        result = subprocess.run(command, cwd=FASERG4_DIR)
    else:
        result = subprocess.run(command, cwd=FASERG4_DIR, input=macro_text.encode())
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
