/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class BasicKinematicConstraint {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BasicKinematicConstraint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BasicKinematicConstraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_BasicKinematicConstraint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BasicKinematicConstraint() {
    this(raveJNI.new_BasicKinematicConstraint(), true);
  }

  public BasicKinematicConstraint clone() {
    long cPtr = raveJNI.BasicKinematicConstraint_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BasicKinematicConstraint(cPtr, false);
  }

  public boolean isValid() {
    return raveJNI.BasicKinematicConstraint_isValid(swigCPtr, this);
  }

}
