/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RavePerigeeParameters5D extends RavePerigeeParameters3D {
  private long swigCPtr;

  protected RavePerigeeParameters5D(long cPtr, boolean cMemoryOwn) {
    super(raveJNI.RavePerigeeParameters5D_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RavePerigeeParameters5D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RavePerigeeParameters5D(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RavePerigeeParameters5D(float rho, float theta, float phip, float epsilon, float zp) {
    this(raveJNI.new_RavePerigeeParameters5D__SWIG_0(rho, theta, phip, epsilon, zp), true);
  }

  public RavePerigeeParameters5D(RavePerigeeParameters3D arg0, float epsilon, float zp) {
    this(raveJNI.new_RavePerigeeParameters5D__SWIG_1(RavePerigeeParameters3D.getCPtr(arg0), arg0, epsilon, zp), true);
  }

  public RavePerigeeParameters5D() {
    this(raveJNI.new_RavePerigeeParameters5D__SWIG_2(), true);
  }

  public float epsilon() {
    return raveJNI.RavePerigeeParameters5D_epsilon(swigCPtr, this);
  }

  public float zp() {
    return raveJNI.RavePerigeeParameters5D_zp(swigCPtr, this);
  }

  public boolean equal(RavePerigeeParameters5D other) {
    return raveJNI.RavePerigeeParameters5D_equal(swigCPtr, this, RavePerigeeParameters5D.getCPtr(other), other);
  }

}
