/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveFlavorTagFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveFlavorTagFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveFlavorTagFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveFlavorTagFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveFlavorTagFactory(RaveMagneticField f, String method, String vertexingmethod) {
    this(raveJNI.new_RaveFlavorTagFactory__SWIG_0(RaveMagneticField.getCPtr(f), f, method, vertexingmethod), true);
  }

  public RaveFlavorTagFactory(RaveMagneticField f, String method) {
    this(raveJNI.new_RaveFlavorTagFactory__SWIG_1(RaveMagneticField.getCPtr(f), f, method), true);
  }

  public RaveFlavorTagFactory(RaveMagneticField f) {
    this(raveJNI.new_RaveFlavorTagFactory__SWIG_2(RaveMagneticField.getCPtr(f), f), true);
  }

  public RaveFlavorTagFactory(RaveVertexFactory f, String method) {
    this(raveJNI.new_RaveFlavorTagFactory__SWIG_3(RaveVertexFactory.getCPtr(f), f, method), true);
  }

  public RaveFlavorTagFactory(RaveVertexFactory f) {
    this(raveJNI.new_RaveFlavorTagFactory__SWIG_4(RaveVertexFactory.getCPtr(f), f), true);
  }

  public float tag(RaveTrackContainer tracks, RaveVertex primary, RavePoint3D jet) {
    return raveJNI.RaveFlavorTagFactory_tag(swigCPtr, this, RaveTrackContainer.getCPtr(tracks), tracks, RaveVertex.getCPtr(primary), primary, RavePoint3D.getCPtr(jet), jet);
  }

  public boolean hasFlavorTagging() {
    return raveJNI.RaveFlavorTagFactory_hasFlavorTagging(swigCPtr, this);
  }

  public void resetBeamSpot() {
    raveJNI.RaveFlavorTagFactory_resetBeamSpot(swigCPtr, this);
  }

}
