/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveException {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveException(String arg0) {
    this(raveJNI.new_RaveException(arg0), true);
  }

  public String what() {
    return raveJNI.RaveException_what(swigCPtr, this);
  }

}
