/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class rave {
  public static boolean RaveEquals(RavePoint3D lhs, RavePoint3D rhs) {
    return raveJNI.RaveEquals__SWIG_0(RavePoint3D.getCPtr(lhs), lhs, RavePoint3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveVector6D lhs, RaveVector6D rhs) {
    return raveJNI.RaveEquals__SWIG_1(RaveVector6D.getCPtr(lhs), lhs, RaveVector6D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance3D lhs, RaveCovariance3D rhs) {
    return raveJNI.RaveEquals__SWIG_2(RaveCovariance3D.getCPtr(lhs), lhs, RaveCovariance3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance33D lhs, RaveCovariance33D rhs) {
    return raveJNI.RaveEquals__SWIG_3(RaveCovariance33D.getCPtr(lhs), lhs, RaveCovariance33D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance6D lhs, RaveCovariance6D rhs) {
    return raveJNI.RaveEquals__SWIG_4(RaveCovariance6D.getCPtr(lhs), lhs, RaveCovariance6D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RavePerigeeParameters3D lhs, RavePerigeeParameters3D rhs) {
    return raveJNI.RaveEquals__SWIG_5(RavePerigeeParameters3D.getCPtr(lhs), lhs, RavePerigeeParameters3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RavePerigeeParameters5D lhs, RavePerigeeParameters5D rhs) {
    return raveJNI.RaveEquals__SWIG_6(RavePerigeeParameters5D.getCPtr(lhs), lhs, RavePerigeeParameters5D.getCPtr(rhs), rhs);
  }

  public static String RaveVersion() {
    return raveJNI.RaveVersion();
  }

  public static float getCentimeter() {
    return raveJNI.centimeter_get();
  }

  public static float getMillimeter() {
    return raveJNI.millimeter_get();
  }

  public static float getMeter() {
    return raveJNI.meter_get();
  }

  public static float getMicrometer() {
    return raveJNI.micrometer_get();
  }

  public static float getNanometer() {
    return raveJNI.nanometer_get();
  }

  public static float getNm() {
    return raveJNI.nm_get();
  }

  public static float getUm() {
    return raveJNI.um_get();
  }

  public static float getMm() {
    return raveJNI.mm_get();
  }

  public static float getCm() {
    return raveJNI.cm_get();
  }

  public static float getM() {
    return raveJNI.m_get();
  }

  public static float getSecond() {
    return raveJNI.second_get();
  }

  public static float getNanosecond() {
    return raveJNI.nanosecond_get();
  }

  public static float getMillisecond() {
    return raveJNI.millisecond_get();
  }

  public static float getMicrosecond() {
    return raveJNI.microsecond_get();
  }

  public static float getNs() {
    return raveJNI.ns_get();
  }

  public static float getS() {
    return raveJNI.s_get();
  }

  public static float getMs() {
    return raveJNI.ms_get();
  }

  public static float getGigaelectronvolt() {
    return raveJNI.gigaelectronvolt_get();
  }

  public static float getMegaelectronvolt() {
    return raveJNI.megaelectronvolt_get();
  }

  public static float getKiloelectronvolt() {
    return raveJNI.kiloelectronvolt_get();
  }

  public static float getElectronvolt() {
    return raveJNI.electronvolt_get();
  }

  public static float getTeraelectronvolt() {
    return raveJNI.teraelectronvolt_get();
  }

  public static float getMeV() {
    return raveJNI.MeV_get();
  }

  public static float getEV() {
    return raveJNI.eV_get();
  }

  public static float getKeV() {
    return raveJNI.keV_get();
  }

  public static float getGeV() {
    return raveJNI.GeV_get();
  }

  public static float getTeV() {
    return raveJNI.TeV_get();
  }

  public static float getRad() {
    return raveJNI.rad_get();
  }

  public static float getMillirad() {
    return raveJNI.millirad_get();
  }

  public static float getMrad() {
    return raveJNI.mrad_get();
  }

  public static float getSpeedoflight() {
    return raveJNI.speedoflight_get();
  }

  public static float getC() {
    return raveJNI.c_get();
  }

  public static float getTesla() {
    return raveJNI.Tesla_get();
  }

  public static float getGauss() {
    return raveJNI.Gauss_get();
  }

  public static float getKGauss() {
    return raveJNI.kGauss_get();
  }

  public static boolean RaveEquals(RaveVector4D lhs, RaveVector4D rhs) {
    return raveJNI.RaveEquals__SWIG_7(RaveVector4D.getCPtr(lhs), lhs, RaveVector4D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveVector7D lhs, RaveVector7D rhs) {
    return raveJNI.RaveEquals__SWIG_8(RaveVector7D.getCPtr(lhs), lhs, RaveVector7D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance4D lhs, RaveCovariance4D rhs) {
    return raveJNI.RaveEquals__SWIG_9(RaveCovariance4D.getCPtr(lhs), lhs, RaveCovariance4D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance7D lhs, RaveCovariance7D rhs) {
    return raveJNI.RaveEquals__SWIG_10(RaveCovariance7D.getCPtr(lhs), lhs, RaveCovariance7D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RavePerigeeParameters6D lhs, RavePerigeeParameters6D rhs) {
    return raveJNI.RaveEquals__SWIG_11(RavePerigeeParameters6D.getCPtr(lhs), lhs, RavePerigeeParameters6D.getCPtr(rhs), rhs);
  }

}
