/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveKTreeContainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveKTreeContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveKTreeContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveKTreeContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveKTreeContainer() {
    this(raveJNI.new_RaveKTreeContainer__SWIG_0(), true);
  }

  public RaveKTreeContainer(long n) {
    this(raveJNI.new_RaveKTreeContainer__SWIG_1(n), true);
  }

  public long size() {
    return raveJNI.RaveKTreeContainer_size(swigCPtr, this);
  }

  public long capacity() {
    return raveJNI.RaveKTreeContainer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    raveJNI.RaveKTreeContainer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return raveJNI.RaveKTreeContainer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    raveJNI.RaveKTreeContainer_clear(swigCPtr, this);
  }

  public void add(RaveKTree x) {
    raveJNI.RaveKTreeContainer_add(swigCPtr, this, RaveKTree.getCPtr(x), x);
  }

  public RaveKTree get(int i) {
    return new RaveKTree(raveJNI.RaveKTreeContainer_get(swigCPtr, this, i), false);
  }

  public void set(int i, RaveKTree val) {
    raveJNI.RaveKTreeContainer_set(swigCPtr, this, i, RaveKTree.getCPtr(val), val);
  }

}
