/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RavePerigeeCovariance6D extends RavePerigeeCovariance5D {
  private long swigCPtr;

  protected RavePerigeeCovariance6D(long cPtr, boolean cMemoryOwn) {
    super(raveJNI.RavePerigeeCovariance6D_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RavePerigeeCovariance6D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RavePerigeeCovariance6D(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RavePerigeeCovariance6D(float drr, float drt, float drp, float dre, float drz, float drm, float dtt, float dtp, float dte, float dtz, float dtm, float dpp, float dpe, float dpz, float dpm, float dee, float dez, float dem, float dzz, float dzm, float dmm) {
    this(raveJNI.new_RavePerigeeCovariance6D__SWIG_0(drr, drt, drp, dre, drz, drm, dtt, dtp, dte, dtz, dtm, dpp, dpe, dpz, dpm, dee, dez, dem, dzz, dzm, dmm), true);
  }

  public RavePerigeeCovariance6D(RavePerigeeCovariance5D arg0, float drm, float dtm, float dpm, float dem, float dzm, float dmm) {
    this(raveJNI.new_RavePerigeeCovariance6D__SWIG_1(RavePerigeeCovariance5D.getCPtr(arg0), arg0, drm, dtm, dpm, dem, dzm, dmm), true);
  }

  public RavePerigeeCovariance6D() {
    this(raveJNI.new_RavePerigeeCovariance6D__SWIG_2(), true);
  }

  public float drm() {
    return raveJNI.RavePerigeeCovariance6D_drm(swigCPtr, this);
  }

  public float dtm() {
    return raveJNI.RavePerigeeCovariance6D_dtm(swigCPtr, this);
  }

  public float dpm() {
    return raveJNI.RavePerigeeCovariance6D_dpm(swigCPtr, this);
  }

  public float dem() {
    return raveJNI.RavePerigeeCovariance6D_dem(swigCPtr, this);
  }

  public float dzm() {
    return raveJNI.RavePerigeeCovariance6D_dzm(swigCPtr, this);
  }

  public float dmm() {
    return raveJNI.RavePerigeeCovariance6D_dmm(swigCPtr, this);
  }

  public String toString() {
    return raveJNI.RavePerigeeCovariance6D_toString(swigCPtr, this);
  }

  public String __str__() {
    return raveJNI.RavePerigeeCovariance6D___str__(swigCPtr, this);
  }

}
