/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveVertexContainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveVertexContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveVertexContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveVertexContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveVertexContainer() {
    this(raveJNI.new_RaveVertexContainer__SWIG_0(), true);
  }

  public RaveVertexContainer(long n) {
    this(raveJNI.new_RaveVertexContainer__SWIG_1(n), true);
  }

  public long size() {
    return raveJNI.RaveVertexContainer_size(swigCPtr, this);
  }

  public long capacity() {
    return raveJNI.RaveVertexContainer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    raveJNI.RaveVertexContainer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return raveJNI.RaveVertexContainer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    raveJNI.RaveVertexContainer_clear(swigCPtr, this);
  }

  public void add(RaveVertex x) {
    raveJNI.RaveVertexContainer_add(swigCPtr, this, RaveVertex.getCPtr(x), x);
  }

  public RaveVertex get(int i) {
    return new RaveVertex(raveJNI.RaveVertexContainer_get(swigCPtr, this, i), false);
  }

  public void set(int i, RaveVertex val) {
    raveJNI.RaveVertexContainer_set(swigCPtr, this, i, RaveVertex.getCPtr(val), val);
  }

}
