/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveVector4D extends RavePoint3D {
  private long swigCPtr;

  protected RaveVector4D(long cPtr, boolean cMemoryOwn) {
    super(raveJNI.RaveVector4D_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveVector4D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveVector4D(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RaveVector4D(float x, float y, float z, float m) {
    this(raveJNI.new_RaveVector4D__SWIG_0(x, y, z, m), true);
  }

  public RaveVector4D(RavePoint3D v, float m) {
    this(raveJNI.new_RaveVector4D__SWIG_1(RavePoint3D.getCPtr(v), v, m), true);
  }

  public RaveVector4D() {
    this(raveJNI.new_RaveVector4D__SWIG_2(), true);
  }

  public float m() {
    return raveJNI.RaveVector4D_m(swigCPtr, this);
  }

  public float energy() {
    return raveJNI.RaveVector4D_energy(swigCPtr, this);
  }

  public boolean equal(RaveVector4D arg0) {
    return raveJNI.RaveVector4D_equal(swigCPtr, this, RaveVector4D.getCPtr(arg0), arg0);
  }

  public void add(RaveVector4D other) {
    raveJNI.RaveVector4D_add(swigCPtr, this, RaveVector4D.getCPtr(other), other);
  }

  public void subtract(RaveVector4D other) {
    raveJNI.RaveVector4D_subtract(swigCPtr, this, RaveVector4D.getCPtr(other), other);
  }

  public RavePoint3D p3() {
    return new RavePoint3D(raveJNI.RaveVector4D_p3(swigCPtr, this), true);
  }

  public String toString() {
    return raveJNI.RaveVector4D_toString(swigCPtr, this);
  }

  public String __str__() {
    return raveJNI.RaveVector4D___str__(swigCPtr, this);
  }

}
