/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveVertexFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveVertexFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveVertexFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveVertexFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveVertexFactory(RaveMagneticField m, RavePropagator p, String method, int verbosity) {
    this(raveJNI.new_RaveVertexFactory__SWIG_0(RaveMagneticField.getCPtr(m), m, RavePropagator.getCPtr(p), p, method, verbosity), true);
  }

  public RaveVertexFactory(RaveMagneticField m, RavePropagator p, String method) {
    this(raveJNI.new_RaveVertexFactory__SWIG_1(RaveMagneticField.getCPtr(m), m, RavePropagator.getCPtr(p), p, method), true);
  }

  public RaveVertexFactory(RaveMagneticField m, RavePropagator p) {
    this(raveJNI.new_RaveVertexFactory__SWIG_2(RaveMagneticField.getCPtr(m), m, RavePropagator.getCPtr(p), p), true);
  }

  public RaveVertexFactory(RaveMagneticField m) {
    this(raveJNI.new_RaveVertexFactory__SWIG_3(RaveMagneticField.getCPtr(m), m), true);
  }

  public RaveVertexFactory() {
    this(raveJNI.new_RaveVertexFactory__SWIG_4(), true);
  }

  public RaveVertexFactory(RaveMagneticField arg0, RavePropagator arg1, RaveEllipsoid3D beamspot, String method, int verbosity) {
    this(raveJNI.new_RaveVertexFactory__SWIG_5(RaveMagneticField.getCPtr(arg0), arg0, RavePropagator.getCPtr(arg1), arg1, RaveEllipsoid3D.getCPtr(beamspot), beamspot, method, verbosity), true);
  }

  public RaveVertexFactory(RaveMagneticField arg0, RavePropagator arg1, RaveEllipsoid3D beamspot, String method) {
    this(raveJNI.new_RaveVertexFactory__SWIG_6(RaveMagneticField.getCPtr(arg0), arg0, RavePropagator.getCPtr(arg1), arg1, RaveEllipsoid3D.getCPtr(beamspot), beamspot, method), true);
  }

  public RaveVertexFactory(RaveMagneticField arg0, RavePropagator arg1, RaveEllipsoid3D beamspot) {
    this(raveJNI.new_RaveVertexFactory__SWIG_7(RaveMagneticField.getCPtr(arg0), arg0, RavePropagator.getCPtr(arg1), arg1, RaveEllipsoid3D.getCPtr(beamspot), beamspot), true);
  }

  public RaveVertexFactory(RaveVertexFactory o) {
    this(raveJNI.new_RaveVertexFactory__SWIG_8(RaveVertexFactory.getCPtr(o), o), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_0(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_1(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RavePoint3D seed, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_2(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RavePoint3D.getCPtr(seed), seed, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RavePoint3D seed) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_3(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RavePoint3D.getCPtr(seed), seed), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RaveTrack ghost_track, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_4(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RaveTrack.getCPtr(ghost_track), ghost_track, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RaveTrack ghost_track) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_5(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RaveTrack.getCPtr(ghost_track), ghost_track), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_6(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_7(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, RaveTrack ghost_track, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_8(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, RaveTrack.getCPtr(ghost_track), ghost_track, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, RaveTrack ghost_track) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_9(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, RaveTrack.getCPtr(ghost_track), ghost_track), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, String method, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_10(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, method, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, String method) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_11(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, method), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RavePoint3D seed, String method, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_12(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RavePoint3D.getCPtr(seed), seed, method, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, RavePoint3D seed, String method) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_13(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, RavePoint3D.getCPtr(seed), seed, method), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, String method, RaveTrack ghost_track, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_14(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, method, RaveTrack.getCPtr(ghost_track), ghost_track, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer arg0, String method, RaveTrack ghost_track) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_15(swigCPtr, this, RaveTrackContainer.getCPtr(arg0), arg0, method, RaveTrack.getCPtr(ghost_track), ghost_track), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, String method, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_16(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, method, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, String method) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_17(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, method), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, String method, RaveTrack ghost_track, boolean use_beamspot) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_18(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, method, RaveTrack.getCPtr(ghost_track), ghost_track, use_beamspot), true);
  }

  public RaveVertexContainer create(RaveTrackContainer primaries, RaveTrackContainer tracks, String method, RaveTrack ghost_track) {
    return new RaveVertexContainer(raveJNI.RaveVertexFactory_create__SWIG_19(swigCPtr, this, RaveTrackContainer.getCPtr(primaries), primaries, RaveTrackContainer.getCPtr(tracks), tracks, method, RaveTrack.getCPtr(ghost_track), ghost_track), true);
  }

  public RavePropagator getPropagator() {
    return new RavePropagator(raveJNI.RaveVertexFactory_getPropagator(swigCPtr, this), false);
  }

  public RaveMagneticField getMagneticField() {
    return new RaveMagneticField(raveJNI.RaveVertexFactory_getMagneticField(swigCPtr, this), false);
  }

  public RaveEllipsoid3D getBeamspot() {
    return new RaveEllipsoid3D(raveJNI.RaveVertexFactory_getBeamspot(swigCPtr, this), false);
  }

  public boolean hasBeamspot() {
    return raveJNI.RaveVertexFactory_hasBeamspot(swigCPtr, this);
  }

  public int verbosity() {
    return raveJNI.RaveVertexFactory_verbosity(swigCPtr, this);
  }

  public String method() {
    return raveJNI.RaveVertexFactory_method(swigCPtr, this);
  }

  public void setDefaultMethod(String arg0) {
    raveJNI.RaveVertexFactory_setDefaultMethod(swigCPtr, this, arg0);
  }

  public void setBeamSpot(RaveEllipsoid3D arg0) {
    raveJNI.RaveVertexFactory_setBeamSpot(swigCPtr, this, RaveEllipsoid3D.getCPtr(arg0), arg0);
  }

  public SWIGTYPE_p_rave__VertexReconstructor reconstructor() {
    return new SWIGTYPE_p_rave__VertexReconstructor(raveJNI.RaveVertexFactory_reconstructor(swigCPtr, this), false);
  }

  public void init() {
    raveJNI.RaveVertexFactory_init(swigCPtr, this);
  }

  public void wipe() {
    raveJNI.RaveVertexFactory_wipe(swigCPtr, this);
  }

}
