/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveEllipsoid3D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveEllipsoid3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveEllipsoid3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveEllipsoid3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveEllipsoid3D(RavePoint3D arg0, RaveCovariance3D arg1) {
    this(raveJNI.new_RaveEllipsoid3D__SWIG_0(RavePoint3D.getCPtr(arg0), arg0, RaveCovariance3D.getCPtr(arg1), arg1), true);
  }

  public RaveEllipsoid3D() {
    this(raveJNI.new_RaveEllipsoid3D__SWIG_1(), true);
  }

  public RavePoint3D point() {
    return new RavePoint3D(raveJNI.RaveEllipsoid3D_point(swigCPtr, this), false);
  }

  public RaveCovariance3D covariance() {
    return new RaveCovariance3D(raveJNI.RaveEllipsoid3D_covariance(swigCPtr, this), false);
  }

  public boolean isValid() {
    return raveJNI.RaveEllipsoid3D_isValid(swigCPtr, this);
  }

}
