/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RavePerigeeCovariance3D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RavePerigeeCovariance3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RavePerigeeCovariance3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RavePerigeeCovariance3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RavePerigeeCovariance3D(float drr, float drt, float drp, float dtt, float dtp, float dpp) {
    this(raveJNI.new_RavePerigeeCovariance3D__SWIG_0(drr, drt, drp, dtt, dtp, dpp), true);
  }

  public RavePerigeeCovariance3D() {
    this(raveJNI.new_RavePerigeeCovariance3D__SWIG_1(), true);
  }

  public float drr() {
    return raveJNI.RavePerigeeCovariance3D_drr(swigCPtr, this);
  }

  public float drt() {
    return raveJNI.RavePerigeeCovariance3D_drt(swigCPtr, this);
  }

  public float drp() {
    return raveJNI.RavePerigeeCovariance3D_drp(swigCPtr, this);
  }

  public float dtt() {
    return raveJNI.RavePerigeeCovariance3D_dtt(swigCPtr, this);
  }

  public float dtp() {
    return raveJNI.RavePerigeeCovariance3D_dtp(swigCPtr, this);
  }

  public float dpp() {
    return raveJNI.RavePerigeeCovariance3D_dpp(swigCPtr, this);
  }

}
