/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveTrackContainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveTrackContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveTrackContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveTrackContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveTrackContainer() {
    this(raveJNI.new_RaveTrackContainer__SWIG_0(), true);
  }

  public RaveTrackContainer(long n) {
    this(raveJNI.new_RaveTrackContainer__SWIG_1(n), true);
  }

  public long size() {
    return raveJNI.RaveTrackContainer_size(swigCPtr, this);
  }

  public long capacity() {
    return raveJNI.RaveTrackContainer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    raveJNI.RaveTrackContainer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return raveJNI.RaveTrackContainer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    raveJNI.RaveTrackContainer_clear(swigCPtr, this);
  }

  public void add(RaveTrack x) {
    raveJNI.RaveTrackContainer_add(swigCPtr, this, RaveTrack.getCPtr(x), x);
  }

  public RaveTrack get(int i) {
    return new RaveTrack(raveJNI.RaveTrackContainer_get(swigCPtr, this, i), false);
  }

  public void set(int i, RaveTrack val) {
    raveJNI.RaveTrackContainer_set(swigCPtr, this, i, RaveTrack.getCPtr(val), val);
  }

}
