/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RavePerigeeParameters3D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RavePerigeeParameters3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RavePerigeeParameters3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RavePerigeeParameters3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RavePerigeeParameters3D(float rho, float theta, float phip) {
    this(raveJNI.new_RavePerigeeParameters3D__SWIG_0(rho, theta, phip), true);
  }

  public RavePerigeeParameters3D() {
    this(raveJNI.new_RavePerigeeParameters3D__SWIG_1(), true);
  }

  public float rho() {
    return raveJNI.RavePerigeeParameters3D_rho(swigCPtr, this);
  }

  public float theta() {
    return raveJNI.RavePerigeeParameters3D_theta(swigCPtr, this);
  }

  public float phip() {
    return raveJNI.RavePerigeeParameters3D_phip(swigCPtr, this);
  }

  public boolean equal(RavePerigeeParameters3D other) {
    return raveJNI.RavePerigeeParameters3D_equal(swigCPtr, this, RavePerigeeParameters3D.getCPtr(other), other);
  }

}
