/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveCovariance3D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveCovariance3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveCovariance3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveCovariance3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveCovariance3D(float dxx, float dxy, float dxz, float dyy, float dyz, float dzz) {
    this(raveJNI.new_RaveCovariance3D__SWIG_0(dxx, dxy, dxz, dyy, dyz, dzz), true);
  }

  public RaveCovariance3D() {
    this(raveJNI.new_RaveCovariance3D__SWIG_1(), true);
  }

  public float dxx() {
    return raveJNI.RaveCovariance3D_dxx(swigCPtr, this);
  }

  public float dxy() {
    return raveJNI.RaveCovariance3D_dxy(swigCPtr, this);
  }

  public float dxz() {
    return raveJNI.RaveCovariance3D_dxz(swigCPtr, this);
  }

  public float dyy() {
    return raveJNI.RaveCovariance3D_dyy(swigCPtr, this);
  }

  public float dyz() {
    return raveJNI.RaveCovariance3D_dyz(swigCPtr, this);
  }

  public float dzz() {
    return raveJNI.RaveCovariance3D_dzz(swigCPtr, this);
  }

  public boolean equal(RaveCovariance3D other) {
    return raveJNI.RaveCovariance3D_equal(swigCPtr, this, RaveCovariance3D.getCPtr(other), other);
  }

  public String toString() {
    return raveJNI.RaveCovariance3D_toString(swigCPtr, this);
  }

  public String __str__() {
    return raveJNI.RaveCovariance3D___str__(swigCPtr, this);
  }

}
