/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class RaveKParticle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RaveKParticle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RaveKParticle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_RaveKParticle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RaveKParticle() {
    this(raveJNI.new_RaveKParticle__SWIG_1(), true);
  }

  public RaveVector7D fullstate() {
    return new RaveVector7D(raveJNI.RaveKParticle_fullstate(swigCPtr, this), false);
  }

  public RaveVector4D p4() {
    return new RaveVector4D(raveJNI.RaveKParticle_p4(swigCPtr, this), false);
  }

  public RaveCovariance7D fullerror() {
    return new RaveCovariance7D(raveJNI.RaveKParticle_fullerror(swigCPtr, this), false);
  }

  public RaveVector6D state() {
    return new RaveVector6D(raveJNI.RaveKParticle_state(swigCPtr, this), false);
  }

  public RaveCovariance6D error() {
    return new RaveCovariance6D(raveJNI.RaveKParticle_error(swigCPtr, this), false);
  }

  public int charge() {
    return raveJNI.RaveKParticle_charge(swigCPtr, this);
  }

  public RavePerigeeParameters5D perigeeParameters() {
    return new RavePerigeeParameters5D(raveJNI.RaveKParticle_perigeeParameters(swigCPtr, this), false);
  }

  public RavePerigeeCovariance5D perigeeCovariance() {
    return new RavePerigeeCovariance5D(raveJNI.RaveKParticle_perigeeCovariance(swigCPtr, this), false);
  }

  public RavePerigeeParameters6D fullPerigeeParameters() {
    return new RavePerigeeParameters6D(raveJNI.RaveKParticle_fullPerigeeParameters(swigCPtr, this), false);
  }

  public RavePerigeeCovariance6D fullPerigeeCovariance() {
    return new RavePerigeeCovariance6D(raveJNI.RaveKParticle_fullPerigeeCovariance(swigCPtr, this), false);
  }

  public float chi2() {
    return raveJNI.RaveKParticle_chi2(swigCPtr, this);
  }

  public float ndof() {
    return raveJNI.RaveKParticle_ndof(swigCPtr, this);
  }

  public SWIGTYPE_p_boost__shared_ptrT_rave__MagneticField_t magneticField() {
    return new SWIGTYPE_p_boost__shared_ptrT_rave__MagneticField_t(raveJNI.RaveKParticle_magneticField(swigCPtr, this), true);
  }

  public SWIGTYPE_p_boost__shared_ptrT_rave__KinematicConstraint_t lastConstraint() {
    return new SWIGTYPE_p_boost__shared_ptrT_rave__KinematicConstraint_t(raveJNI.RaveKParticle_lastConstraint(swigCPtr, this), true);
  }

  public int id() {
    return raveJNI.RaveKParticle_id(swigCPtr, this);
  }

  public SWIGTYPE_p_boost__any link() {
    return new SWIGTYPE_p_boost__any(raveJNI.RaveKParticle_link(swigCPtr, this), true);
  }

  public String tag() {
    return raveJNI.RaveKParticle_tag(swigCPtr, this);
  }

  public boolean isValid() {
    return raveJNI.RaveKParticle_isValid(swigCPtr, this);
  }

  public void unlink() {
    raveJNI.RaveKParticle_unlink(swigCPtr, this);
  }

  public String toString() {
    return raveJNI.RaveKParticle_toString(swigCPtr, this);
  }

  public String __str__() {
    return raveJNI.RaveKParticle___str__(swigCPtr, this);
  }

}
