/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class WeightedRaveTrack {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WeightedRaveTrack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedRaveTrack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_WeightedRaveTrack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WeightedRaveTrack() {
    this(raveJNI.new_WeightedRaveTrack__SWIG_0(), true);
  }

  public WeightedRaveTrack(float first, RaveTrack second) {
    this(raveJNI.new_WeightedRaveTrack__SWIG_1(first, RaveTrack.getCPtr(second), second), true);
  }

  public WeightedRaveTrack(WeightedRaveTrack p) {
    this(raveJNI.new_WeightedRaveTrack__SWIG_2(WeightedRaveTrack.getCPtr(p), p), true);
  }

  public void setFirst(float value) {
    raveJNI.WeightedRaveTrack_first_set(swigCPtr, this, value);
  }

  public float getFirst() {
    return raveJNI.WeightedRaveTrack_first_get(swigCPtr, this);
  }

  public void setSecond(RaveTrack value) {
    raveJNI.WeightedRaveTrack_second_set(swigCPtr, this, RaveTrack.getCPtr(value), value);
  }

  public RaveTrack getSecond() {
    long cPtr = raveJNI.WeightedRaveTrack_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RaveTrack(cPtr, false);
  }

}
