/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class WeightedRaveTrackContainer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WeightedRaveTrackContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WeightedRaveTrackContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        raveJNI.delete_WeightedRaveTrackContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WeightedRaveTrackContainer() {
    this(raveJNI.new_WeightedRaveTrackContainer__SWIG_0(), true);
  }

  public WeightedRaveTrackContainer(long n) {
    this(raveJNI.new_WeightedRaveTrackContainer__SWIG_1(n), true);
  }

  public long size() {
    return raveJNI.WeightedRaveTrackContainer_size(swigCPtr, this);
  }

  public long capacity() {
    return raveJNI.WeightedRaveTrackContainer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    raveJNI.WeightedRaveTrackContainer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return raveJNI.WeightedRaveTrackContainer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    raveJNI.WeightedRaveTrackContainer_clear(swigCPtr, this);
  }

  public void add(WeightedRaveTrack x) {
    raveJNI.WeightedRaveTrackContainer_add(swigCPtr, this, WeightedRaveTrack.getCPtr(x), x);
  }

  public WeightedRaveTrack get(int i) {
    return new WeightedRaveTrack(raveJNI.WeightedRaveTrackContainer_get(swigCPtr, this, i), false);
  }

  public void set(int i, WeightedRaveTrack val) {
    raveJNI.WeightedRaveTrackContainer_set(swigCPtr, this, i, WeightedRaveTrack.getCPtr(val), val);
  }

}
