# Macro example
# tilted geometry
/FASER/scint/material PVT
/FASER/scint/lightYield 12000.
/FASER/scint/sizeX 48 cm
/FASER/scint/sizeY 48 cm
/FASER/scint/sizeZ 20 cm
/FASER/scint/voxel 10 mm
/FASER/targetW/sizeX 48 cm
/FASER/targetW/sizeY 48 cm
/FASER/targetW/sizeZ 5 mm
/FASER/layers 10
# Shift only the 3DCAL by -5 cm in X and Y
/FASER/LOS/shiftX 22 cm #22 cm
/FASER/LOS/shiftY 17 cm #17 cm
# NEW: tilt everything by -5 degrees around Y
#/FASER/tiltY 0 deg
/FASER/tiltY -4.5 deg
#
/tracking/verbose 0
/mdt/verbose 0
/run/verbose 0
/control/verbose 0
#/process/optical/processActivation Cerenkov false
/run/numberOfThreads 1
/run/initialize
/generator/rootinputfilename /home/rubbiaa/FASERV6/TILTED/FASER/FASERG4/../ConvertGENIE/FASERMC-PO-Run501-0_1255174.root
/generator/startevent 0
/run/beamOn 1

